# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify

default_stages: [pre-commit, pre-merge-commit]
default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit, pre-merge-commit, manual]
        args:
          - --maxkb=2000
      - id: check-toml
        stages: [pre-commit, pre-merge-commit, manual]
      - id: check-yaml
        stages: [pre-commit, pre-merge-commit, manual]
        args:
          - --unsafe
      - id: end-of-file-fixer
        stages: [pre-commit, pre-merge-commit, manual]
      - id: trailing-whitespace
        stages: [pre-commit, pre-merge-commit, manual]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        stages: [pre-commit, pre-merge-commit, manual]
        args: [--ignore-words=.codespell-whitelist.txt]

  - repo: local
    hooks:
      - id: lint
        name: Linter
        stages: [pre-commit, pre-merge-commit, manual]
        language: system
        entry: make lint

  - repo: local
    hooks:
      - id: static-analysis
        name: Static analysis
        language: system
        entry: make static

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [
          '--baseline', '.secrets.baseline',
        ]
        exclude: package.lock.json
        stages: [ pre-commit, pre-merge-commit, manual ]
