x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-observability: &observability
  evsoft.observability.enabled: "true"
  evsoft.observability.project: "${APP_PROJECT:-fastid}"
  evsoft.observability.environment: "${APP_ENVIRONMENT:-development}"

services:
  postgres:
    logging: *default-logging
    labels:
      <<: *observability
      evsoft.observability.service: "postgres"

  redis:
    logging: *default-logging
    labels:
      <<: *observability
      evsoft.observability.service: "redis"

  mailpit:
    logging: *default-logging
    labels:
      <<: *observability
      evsoft.observability.service: "mailpit"

  fastid-app:
    logging: *default-logging
    labels:
      <<: *observability
      evsoft.observability.service: "${APP_SERVICE:-fastid}"
