x-logging: &default-logging
  driver: loki
  options:
    loki-url: '${LOKI_URL:-http://localhost:3100/api/prom/push}'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'

services:
  postgres:
    logging: *default-logging
  redis:
    logging: *default-logging
  mailpit:
    logging: *default-logging
  fastid-app:
    logging: *default-logging

networks:
  default:
    name: observability_net
    external: true
