services:
  fastid-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
  fastid-webhook-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
