"""empty message

Revision ID: 7eb88ab78714
Revises: 5ee810fadd8e
Create Date: 2024-09-05 20:37:32.723760

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7eb88ab78714"
down_revision: str | None = "5ee810fadd8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oidc_accounts", sa.Column("account_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oidc_accounts", "account_id")
    # ### end Alembic commands ###
