"""

Revision ID: cc7037853980
Revises: 446313a37068
Create Date: 2025-04-02 16:04:30.022456

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc7037853980"
down_revision: str | None = "446313a37068"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f("oauth_accounts_user_id_fkey"), "oauth_accounts", "users", ["user_id"], ["id"])
    op.drop_index("users_new_email_idx", table_name="users")
    op.drop_column("users", "new_email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("new_email", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index("users_new_email_idx", "users", ["new_email"], unique=False)
    op.drop_constraint(op.f("oauth_accounts_user_id_fkey"), "oauth_accounts", type_="foreignkey")
    # ### end Alembic commands ###
