"""add_client_id_idx

Revision ID: 3dc1a72c7ad5
Revises: 03244d107aec
Create Date: 2026-06-06 20:07:54.973355

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dc1a72c7ad5"
down_revision: str | None = "03244d107aec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("apps_client_id_idx"), "apps", ["client_id"], unique=False)
    op.create_index(op.f("apps_version_client_id_idx"), "apps_version", ["client_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("apps_version_client_id_idx"), table_name="apps_version")
    op.drop_index(op.f("apps_client_id_idx"), table_name="apps")
    # ### end Alembic commands ###
