"""add_versioning

Revision ID: 18fabf10cb0a
Revises: 0b32faa598cb
Create Date: 2026-01-16 20:14:24.825805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18fabf10cb0a"
down_revision: str | None = "0b32faa598cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apps_version",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("slug", sa.String(), autoincrement=False, nullable=True),
        sa.Column("client_id", sa.String(), autoincrement=False, nullable=True),
        sa.Column("client_secret", sa.String(), autoincrement=False, nullable=True),
        sa.Column("redirect_uris", sa.String(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("apps_version_pkey")),
    )
    op.create_index(op.f("apps_version_end_transaction_id_idx"), "apps_version", ["end_transaction_id"], unique=False)
    op.create_index(op.f("apps_version_operation_type_idx"), "apps_version", ["operation_type"], unique=False)
    op.create_index(op.f("apps_version_transaction_id_idx"), "apps_version", ["transaction_id"], unique=False)
    op.create_table(
        "email_templates_version",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.String(), autoincrement=False, nullable=True),
        sa.Column("subject", sa.String(), autoincrement=False, nullable=True),
        sa.Column("source", sa.String(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("email_templates_version_pkey")),
    )
    op.create_index(
        op.f("email_templates_version_end_transaction_id_idx"),
        "email_templates_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("email_templates_version_operation_type_idx"), "email_templates_version", ["operation_type"], unique=False
    )
    op.create_index(
        op.f("email_templates_version_transaction_id_idx"), "email_templates_version", ["transaction_id"], unique=False
    )
    op.create_table(
        "telegram_templates_version",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.String(), autoincrement=False, nullable=True),
        sa.Column("source", sa.String(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("telegram_templates_version_pkey")),
    )
    op.create_index(
        op.f("telegram_templates_version_end_transaction_id_idx"),
        "telegram_templates_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("telegram_templates_version_operation_type_idx"),
        "telegram_templates_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("telegram_templates_version_transaction_id_idx"),
        "telegram_templates_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "users_version",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("email", sa.String(), autoincrement=False, nullable=True),
        sa.Column("telegram_id", sa.BigInteger(), autoincrement=False, nullable=True),
        sa.Column("hashed_password", sa.String(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("is_superuser", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("is_verified", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("users_version_pkey")),
    )
    op.create_index(op.f("users_version_email_idx"), "users_version", ["email"], unique=False)
    op.create_index(op.f("users_version_end_transaction_id_idx"), "users_version", ["end_transaction_id"], unique=False)
    op.create_index(op.f("users_version_operation_type_idx"), "users_version", ["operation_type"], unique=False)
    op.create_index(op.f("users_version_telegram_id_idx"), "users_version", ["telegram_id"], unique=False)
    op.create_index(op.f("users_version_transaction_id_idx"), "users_version", ["transaction_id"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("remote_addr", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("transaction_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("transaction_pkey")),
    )
    op.create_index(op.f("transaction_user_id_idx"), "transaction", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("transaction_user_id_idx"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("users_version_transaction_id_idx"), table_name="users_version")
    op.drop_index(op.f("users_version_telegram_id_idx"), table_name="users_version")
    op.drop_index(op.f("users_version_operation_type_idx"), table_name="users_version")
    op.drop_index(op.f("users_version_end_transaction_id_idx"), table_name="users_version")
    op.drop_index(op.f("users_version_email_idx"), table_name="users_version")
    op.drop_table("users_version")
    op.drop_index(op.f("telegram_templates_version_transaction_id_idx"), table_name="telegram_templates_version")
    op.drop_index(op.f("telegram_templates_version_operation_type_idx"), table_name="telegram_templates_version")
    op.drop_index(op.f("telegram_templates_version_end_transaction_id_idx"), table_name="telegram_templates_version")
    op.drop_table("telegram_templates_version")
    op.drop_index(op.f("email_templates_version_transaction_id_idx"), table_name="email_templates_version")
    op.drop_index(op.f("email_templates_version_operation_type_idx"), table_name="email_templates_version")
    op.drop_index(op.f("email_templates_version_end_transaction_id_idx"), table_name="email_templates_version")
    op.drop_table("email_templates_version")
    op.drop_index(op.f("apps_version_transaction_id_idx"), table_name="apps_version")
    op.drop_index(op.f("apps_version_operation_type_idx"), table_name="apps_version")
    op.drop_index(op.f("apps_version_end_transaction_id_idx"), table_name="apps_version")
    op.drop_table("apps_version")
    # ### end Alembic commands ###
