"""add_oauth_providers

Revision ID: bfa61bae871d
Revises: 3dc1a72c7ad5
Create Date: 2026-07-16 19:33:35.491894

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa61bae871d"
down_revision: str | None = "3dc1a72c7ad5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_accounts_version",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.Uuid(), autoincrement=False, nullable=True),
        sa.Column("provider", sa.String(), autoincrement=False, nullable=True),
        sa.Column("account_id", sa.String(), autoincrement=False, nullable=True),
        sa.Column("access_token", sa.String(), autoincrement=False, nullable=True),
        sa.Column("expires_in", sa.BigInteger(), autoincrement=False, nullable=True),
        sa.Column("scope", sa.String(), autoincrement=False, nullable=True),
        sa.Column("id_token", sa.String(), autoincrement=False, nullable=True),
        sa.Column("refresh_token", sa.String(), autoincrement=False, nullable=True),
        sa.Column("email", sa.String(), autoincrement=False, nullable=True),
        sa.Column("first_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("display_name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("picture", sa.String(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("oauth_accounts_version_pkey")),
    )
    op.create_index(op.f("oauth_accounts_version_email_idx"), "oauth_accounts_version", ["email"], unique=False)
    op.create_index(
        op.f("oauth_accounts_version_end_transaction_id_idx"),
        "oauth_accounts_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("oauth_accounts_version_operation_type_idx"), "oauth_accounts_version", ["operation_type"], unique=False
    )
    op.create_index(
        op.f("oauth_accounts_version_transaction_id_idx"), "oauth_accounts_version", ["transaction_id"], unique=False
    )
    op.create_index(op.f("oauth_accounts_version_user_id_idx"), "oauth_accounts_version", ["user_id"], unique=False)
    op.create_table(
        "oauth_providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth_providers_pkey")),
        sa.UniqueConstraint("name", name=op.f("oauth_providers_name_key")),
    )
    op.create_table(
        "oauth_providers_version",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("enabled", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("client_id", sa.String(), autoincrement=False, nullable=True),
        sa.Column("client_secret", sa.String(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("oauth_providers_version_pkey")),
    )
    op.create_index(
        op.f("oauth_providers_version_end_transaction_id_idx"),
        "oauth_providers_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("oauth_providers_version_operation_type_idx"), "oauth_providers_version", ["operation_type"], unique=False
    )
    op.create_index(
        op.f("oauth_providers_version_transaction_id_idx"), "oauth_providers_version", ["transaction_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("oauth_providers_version_transaction_id_idx"), table_name="oauth_providers_version")
    op.drop_index(op.f("oauth_providers_version_operation_type_idx"), table_name="oauth_providers_version")
    op.drop_index(op.f("oauth_providers_version_end_transaction_id_idx"), table_name="oauth_providers_version")
    op.drop_table("oauth_providers_version")
    op.drop_table("oauth_providers")
    op.drop_index(op.f("oauth_accounts_version_user_id_idx"), table_name="oauth_accounts_version")
    op.drop_index(op.f("oauth_accounts_version_transaction_id_idx"), table_name="oauth_accounts_version")
    op.drop_index(op.f("oauth_accounts_version_operation_type_idx"), table_name="oauth_accounts_version")
    op.drop_index(op.f("oauth_accounts_version_end_transaction_id_idx"), table_name="oauth_accounts_version")
    op.drop_index(op.f("oauth_accounts_version_email_idx"), table_name="oauth_accounts_version")
    op.drop_table("oauth_accounts_version")
    # ### end Alembic commands ###
