"""update_wh_type

Revision ID: 03244d107aec
Revises: 8d17be37457c
Create Date: 2026-01-19 15:29:07.453246

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03244d107aec"
down_revision: str | None = "8d17be37457c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhooks",
        "type",
        existing_type=sa.VARCHAR(length=17),
        type_=sa.Enum(
            "user_registration",
            "user_login",
            "user_profile_update",
            "user_change_email",
            "user_change_password",
            "user_delete",
            name="webhooktype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "webhooks_version",
        "type",
        existing_type=sa.VARCHAR(length=17),
        type_=sa.Enum(
            "user_registration",
            "user_login",
            "user_profile_update",
            "user_change_email",
            "user_change_password",
            "user_delete",
            name="webhooktype",
            native_enum=False,
        ),
        existing_nullable=True,
        autoincrement=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhooks_version",
        "type",
        existing_type=sa.Enum(
            "user_registration",
            "user_login",
            "user_profile_update",
            "user_change_email",
            "user_change_password",
            "user_delete",
            name="webhooktype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=17),
        existing_nullable=True,
        autoincrement=False,
    )
    op.alter_column(
        "webhooks",
        "type",
        existing_type=sa.Enum(
            "user_registration",
            "user_login",
            "user_profile_update",
            "user_change_email",
            "user_change_password",
            "user_delete",
            name="webhooktype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=17),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
