"""add_webhooks

Revision ID: 771557b57f86
Revises: 18fabf10cb0a
Create Date: 2026-01-19 13:50:54.588101

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "771557b57f86"
down_revision: str | None = "18fabf10cb0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhooks_version",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("app_id", sa.Uuid(), autoincrement=False, nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "user_registration", "user_login", "user_update", "user_delete", name="webhooktype", native_enum=False
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("secret", sa.String(), autoincrement=False, nullable=True),
        sa.Column("url", sa.String(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("webhooks_version_pkey")),
    )
    op.create_index(op.f("webhooks_version_app_id_idx"), "webhooks_version", ["app_id"], unique=False)
    op.create_index(
        op.f("webhooks_version_end_transaction_id_idx"), "webhooks_version", ["end_transaction_id"], unique=False
    )
    op.create_index(op.f("webhooks_version_operation_type_idx"), "webhooks_version", ["operation_type"], unique=False)
    op.create_index(op.f("webhooks_version_transaction_id_idx"), "webhooks_version", ["transaction_id"], unique=False)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("app_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "user_registration", "user_login", "user_update", "user_delete", name="webhooktype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("secret", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["apps.id"], name=op.f("webhooks_app_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("webhooks_pkey")),
    )
    op.create_index(op.f("webhooks_app_id_idx"), "webhooks", ["app_id"], unique=False)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("webhook_id", sa.Uuid(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhooks.id"], name=op.f("webhook_events_webhook_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("webhook_events_pkey")),
    )
    op.create_index(op.f("webhook_events_webhook_id_idx"), "webhook_events", ["webhook_id"], unique=False)
    op.alter_column(
        "notifications",
        "context",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_index(op.f("notifications_user_id_idx"), "notifications", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("notifications_user_id_idx"), table_name="notifications")
    op.alter_column(
        "notifications",
        "context",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_index(op.f("webhook_events_webhook_id_idx"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("webhooks_app_id_idx"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("webhooks_version_transaction_id_idx"), table_name="webhooks_version")
    op.drop_index(op.f("webhooks_version_operation_type_idx"), table_name="webhooks_version")
    op.drop_index(op.f("webhooks_version_end_transaction_id_idx"), table_name="webhooks_version")
    op.drop_index(op.f("webhooks_version_app_id_idx"), table_name="webhooks_version")
    op.drop_table("webhooks_version")
    # ### end Alembic commands ###
