"""

Revision ID: 8d17be37457c
Revises: 771557b57f86
Create Date: 2026-01-19 14:30:09.543616

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d17be37457c"
down_revision: str | None = "771557b57f86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("webhook_events", sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column("webhook_events", sa.Column("status_code", sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_events", "status_code")
    op.drop_column("webhook_events", "request")
    # ### end Alembic commands ###
