"""remove_name_in_templates

Revision ID: 32845277651e
Revises: 81c4895dd132
Create Date: 2026-01-08 15:11:20.789864

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32845277651e"
down_revision: str | None = "81c4895dd132"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_templates", "name")
    op.drop_column("telegram_templates", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telegram_templates", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("email_templates", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
