site_name: FastID
site_description: FastID authentication platform, high security, lightning fast, easy-to-use, customizable
site_url: https://everysoftware.github.io/fastid/

repo_name: everysoftware/fastid
repo_url: https://github.com/everysoftware/fastid
edit_uri: https://github.com/everysoftware/fastid

copyright: Copyright &copy; 2024 - 2025 Stasevich Ivan

docs_dir: docs

extra_css:
  - assets/stylesheets/termynal.css
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/termynal.js
  - assets/javascripts/custom.js

theme:
  name: material
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  i18n:
    prev: 'Previous'
    next: 'Next'
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  favicon: img/favicon.png
  logo: img/favicon.png

plugins:
  - search
  - markdownextradata:
      data: data
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  abbr: null
  attr_list: null
  footnotes: null
  md_in_html: null
  tables: null
  toc:
    permalink: true
  pymdownx.betterem: null
  pymdownx.caret: null
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite: null
  pymdownx.keys: null
  pymdownx.mark: null
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  pymdownx.tilde: null
  pymdownx.blocks.admonition:
    types:
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      - info
      - check
  pymdownx.blocks.details: null
  pymdownx.blocks.tab:
    alternate_style: true
  mdx_include: null
  markdown_include_variants: null

nav:
  - FastID: index.md
  - Overview: overview.md
  - User Guide:
      - tutorial/index.md
      - tutorial/get_started.md
      - tutorial/notifications.md
      - tutorial/social.md
      - tutorial/observability.md
      - tutorial/api.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/everysoftware/fastid
    - icon: fontawesome/solid/globe
      link: https://boosty.to/everysoftware
