name: Docs

on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/docs.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - working-directory: ./docs
        run: poetry run mkdocs gh-deploy --force
